---
jupyter:
  jupytext:
    notebook_metadata_filter: all,-language_info
    split_at_heading: true
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
  kernelspec:
    display_name: R
    language: R
    name: ir
---

# Trying to use R

```{r}
library(pwr)
pwr.anova.test(k=2, n=600, sig.level=0.005, power=0.8)
```

# Let's visualize an image

```{r}
library(RNifti);  # package for NIfTI image reading; https://github.com/jonclayden/RNifti
# plot S1200_AverageT1w_81x96x81.nii.gz from https://osf.io/6hdxv/

img <- readNifti(fname);    # however to refer to S1200_AverageT1w_81x96x81.nii.gz; url("https://osf.io/6hdxv/") maybe?

# the image values are in a 3d array (single anatomical image, not a timeseries)
# can apply many normal functions
dim(img);   # [1] 81 96 81
max(img);  # [1] 1374.128
img[30,20,50];  # value of this voxel

image(img[,,50], col=gray(0:64/64), xlab="", ylab="", axes=FALSE, useRaster=TRUE);   # plot slice k=50
image(img[,20,], col=gray(0:64/64), xlab="", ylab="", axes=FALSE, useRaster=TRUE);   # plot slice j=20

# then similar for gifti? At least loading and getting parcel-average values out, maybe (show how vector, not 3d)

```
