# Book settings
title: "ISMRM'22 QC Book"
author: "The tutorial authors"
copyright: "2022"

# Bibliography settings
bibtex_bibfiles:
  - references.bib

# Sphinx customizations
sphinx:
  extra_extensions:
    - sphinxext.rediraffe

  config:
    nb_custom_formats:
      .Rmd:
        - jupytext.reads
        - fmt: Rmd
    bibtex_reference_style: author_year
    # html_extra_path: ["assets"]
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    rediraffe_redirects:
      auto-qc/iqms_intepretability.md: auto-qc/iqms_interpretability.md


# Execution settings
execute:
  timeout: 3000
  exclude_patterns:
    - 0*ipynb
  execute_notebooks: auto

# HTML-specific settings
html:
  use_repository_button: true
  # use_issues_button: true
  use_edit_page_button: false
  home_page_in_navbar: true

# Launch button settings
launch_buttons:
  notebook_interface: "jupyterlab"
  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  jupyterhub_url: "https://ismrm.dandiarchive.org"
  # The URL of the BinderHub (e.g., https://mybinder.org)
  binderhub_url: "https://mybinder.org"

repository:
  url: https://github.com/nipreps/qc-book
  path_to_book: docs
  branch: main

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

